foreground              #00f0ff
background              #1a1a24
selection_foreground    #050506
selection_background    #ffea00

cursor                  #00f0ff
cursor_text_color       #050506

url_color               #ffb800

active_border_color     #00f0ff
inactive_border_color   #262636
bell_border_color       #ff0055

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #050506
active_tab_background   #00a8ff
inactive_tab_foreground #d0006f
inactive_tab_background #1a1a24
tab_bar_background      #050506

mark1_foreground #050506
mark1_background #00f0ff
mark2_foreground #050506
mark2_background #00ff66
mark3_foreground #050506
mark3_background #ffb800

color0 #262636
color8 #ff007f

color1 #ff0055
color9 #ff0055

color2  #00f0ff
color10 #00a8ff

color3  #ffb800
color11 #ff007f

color4  #00ff66
color12 #ffea00

color5  #00a8ff
color13 #e600ff

color6  #ffea00
color14 #ff007f

color7  #d0006f
color15 #00f0ff
